### ISSUE TITLE
circle-ciのnode, pip

### ISSUE THREAD

**Issue by smellman** [codeforjapan/socialhackday#16]
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.4.4-stretch/node/Dockerfile
nodeは元から8.11.1が現状入っている。
また、pipもdebianのパッケージから入れてよいのではないか

**Comment by halsk** [comment]
ありがとう！ 以下のコミットで対応しました。
d35511df557a2464aca8d8f516636a21f398fea8
31a4bcb4e0be9cfbb5fd426a256d682c03a873a3

**Comment by smellman** [comment]
うーんとpython2系で良いのならいいけど、元がpython3なので、
sudo apt-get install python3-pip python3-dev build-essential
sudo pip3 install awscli --upgrade
かな。
