### ISSUE TITLE
CircleCI がコケる

### ISSUE THREAD

**Issue by halsk** [codeforjapan/socialhackday#28]
```
W: Failed to fetch http://http.us.debian.org/debian/dists/jessie-backports/main/source/Sources  404  Not Found [IP: 208.80.154.15 80]

W: Failed to fetch http://http.us.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 208.80.154.15 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Exited with code 100
```

**Comment by takahashim** [comment]
https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository/508857 この辺の問題でしょうか。

**Comment by halsk** [comment]
PR #29 をマージしたところ冒頭のエラーは消えたが、
今度はこのエラーに。

```

```

**Comment by halsk** [comment]
PR #30 をマージしたら、今度は別のエラーに。

Unable to save binary /home/circleci/repo/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/circleci/repo/node_modules/node-sass/vendor'

**Comment by halsk** [comment]
.circleci/config.yml から、sudo npm install から、sudo を外したら動くようになりました！
@takahashim , @smellman ご協力ありがとうございました！！
